
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team01-f23-6pm-3
owner: ucsb-cs156-f23
repo_name: team01-f23-6pm-3
pull_requests: [{"author":{"id":"U_kgDOBnFNuQ","is_bot":false,"login":"bella-ward","name":"Bella "},"headRefName":"Bella-ZipCode-Controller","number":28,"title":"Add ZipCode Controller and Tests","url":"https://github.com/ucsb-cs156-f23/team01-f23-6pm-3/pull/28"},{"author":{"id":"MDQ6VXNlcjg4MjMzMDc2","is_bot":false,"login":"HououinKyouma-2036","name":"HououinKyouma-2036"},"headRefName":"Leo-Joke-Controller","number":27,"title":"Add Joke Controller and Tests","url":"https://github.com/ucsb-cs156-f23/team01-f23-6pm-3/pull/27"},{"author":{"id":"MDQ6VXNlcjg4MjMzMDc2","is_bot":false,"login":"HououinKyouma-2036","name":"HououinKyouma-2036"},"headRefName":"Leo-Joke","number":26,"title":"Add Joke Service and Tests","url":"https://github.com/ucsb-cs156-f23/team01-f23-6pm-3/pull/26"},{"author":{"id":"U_kgDOBXqLzw","is_bot":false,"login":"erica-ll","name":"Erica Liu"},"headRefName":"Erica-Tides-Controller","number":25,"title":"Add Tides Controller and Tests","url":"https://github.com/ucsb-cs156-f23/team01-f23-6pm-3/pull/25"},{"author":{"id":"U_kgDOBnFNuQ","is_bot":false,"login":"bella-ward","name":"Bella "},"headRefName":"Bella-ZipCode","number":24,"title":"Add ZipCode Service and Tests","url":"https://github.com/ucsb-cs156-f23/team01-f23-6pm-3/pull/24"},{"author":{"id":"U_kgDOB7-lTA","is_bot":false,"login":"YicongYan","name":""},"headRefName":"Yicong-Location-Controller","number":23,"title":"Add location controller and tests","url":"https://github.com/ucsb-cs156-f23/team01-f23-6pm-3/pull/23"},{"author":{"id":"U_kgDOBXqLzw","is_bot":false,"login":"erica-ll","name":"Erica Liu"},"headRefName":"Erica-Tides","number":19,"title":"Add Tides Service and Tests","url":"https://github.com/ucsb-cs156-f23/team01-f23-6pm-3/pull/19"}]
