
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team01-f23-6pm-3
owner: ucsb-cs156-f23
repo_name: team01-f23-6pm-3
pull_requests: [{"author":{"id":"U_kgDOBnFNuQ","is_bot":false,"login":"bella-ward","name":"Bella "},"headRefName":"Bella-GitHub_Pages_1","number":33,"title":"bw - Update 02-gh-pages-rebuild-part-1-backend.yml to fix gh pages fi…","url":"https://github.com/ucsb-cs156-f23/team01-f23-6pm-3/pull/33"}]
