
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team01-f23-6pm-3
owner: ucsb-cs156-f23
repo_name: team01-f23-6pm-3
pull_requests: [{"author":{"id":"U_kgDOBnFNuQ","is_bot":false,"login":"bella-ward","name":"Bella "},"headRefName":"Bella-ZipCode","number":24,"title":"Bella zip code","url":"https://github.com/ucsb-cs156-f23/team01-f23-6pm-3/pull/24"},{"author":{"id":"U_kgDOB7-lTA","is_bot":false,"login":"YicongYan","name":""},"headRefName":"Yicong-Location-Controller","number":23,"title":"Add location controller and tests","url":"https://github.com/ucsb-cs156-f23/team01-f23-6pm-3/pull/23"},{"author":{"id":"MDQ6VXNlcjcwMzQxMDg0","is_bot":false,"login":"Garrett-Hu","name":""},"headRefName":"Garrett-University-Controller","number":22,"title":"Add University Controller + Tests","url":"https://github.com/ucsb-cs156-f23/team01-f23-6pm-3/pull/22"},{"author":{"id":"U_kgDOBsEUwg","is_bot":false,"login":"SalvadorGracia","name":""},"headRefName":"Salvador-PublicHoliday","number":21,"title":"Add Public Holiday Service and Controller","url":"https://github.com/ucsb-cs156-f23/team01-f23-6pm-3/pull/21"},{"author":{"id":"U_kgDOBXqLzw","is_bot":false,"login":"erica-ll","name":"Erica Liu"},"headRefName":"Erica-Tides","number":19,"title":"Add Tides Service and Tests","url":"https://github.com/ucsb-cs156-f23/team01-f23-6pm-3/pull/19"}]
